name: Codex-ready task
description: Tarea lista para delegar a agente.
title: "task: "
labels: ["codex-ready"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objetivo
      description: Resultado concreto.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Alcance
      description: Qué sí / qué no.
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      description: Criterios de aceptación.
    validations:
      required: true
